version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8080:80
    depends_on:
      - app
    container_name: inertia_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    container_name: inertia_app
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    user: "1000:50"
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
        MYSQL_DATABASE: inertia
        MYSQL_ROOT_PASSWORD: root
    ports:
      - 8101:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: inertia_db
